Add unit test v2 for login #80
SWE574-Fall2023-Group1/SWE574-Fall2023-G1 pull request #254
Opened 2023-12-09 20:44 UTC by aykutkantas

Login unit test cases added. Cases are here:

1. renders Login component:
This test checks whether the Login component renders correctly when it's wrapped in a MemoryRouter. It expects that the text 'Welcome' should be present in the rendered component.

2. calls axios.post with correct credentials on form submission:
This test simulates a form submission by changing the values of the username and password fields and clicking the 'Login' button. It then asserts that the axios.post method is called with the correct parameters (username, password, and request configuration) when the form is submitted.

3. handles successful login:
This test checks the handling of a successful login scenario. It mocks the axios.post method to resolve with a status of 201 (simulating a successful login). The test then clicks the 'Login' button and waits for the asynchronous actions to complete.
It expects that the onLoginSuccess callback is called, the text 'Login successful!' is present in the component, and the 'Username' input field is not present in the DOM.

2023-12-09 21:01 UTC, sadikkuzu reviewed
Cannot switch to your development branch

```terminal
$ git checkout --track origin/feature/80-unit-test-execution-v2
error: invalid path 'backend/frontend/src/pages/landing/Login.test.js '
```

Rename that file and clear blank in the end, please.

2023-12-09 21:05 UTC, sadikkuzu requested changes
Could you run this command?:

```
npm run test
```

2023-12-09 21:17 UTC, aykutkantas commented
Yes I could run. Results are here for app.test.js and login.test.js (mine): 

Test Suites: 2 failed, 2 total
Tests:       2 failed, 2 passed, 4 total

For login.test.js others are ok but this case is failed: 

 FAIL  src/pages/landing/Login.test.js
  ● Login component › handles successful login

    expect(element).not.toBeInTheDocument()

    expected document not to contain element, found <input aria-invalid="false" class="MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input" id="login-username" type="text" value="" /> instead

2023-12-09 21:19 UTC, sadikkuzu reviewed
@aykutkantas hi,

i ran
```
cd backend/frontend
npm install
npm run test
```

and i got this:

![sistem-bulamiyor](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/4c83b8bc-a4e0-46f4-8ebc-879cf90a6678)

---

what should i do to overcome this warning?

2023-12-09 21:20 UTC, sadikkuzu commented
> Yes I could run. Results are here for app.test.js and login.test.js (mine):
> 
> Test Suites: 2 failed, 2 total Tests: 2 failed, 2 passed, 4 total
> 
> For login.test.js others are ok but this case is failed:
> 
> FAIL src/pages/landing/Login.test.js ● Login component › handles successful login
> 
> ```
> expect(element).not.toBeInTheDocument()
> 
> expected document not to contain element, found <input aria-invalid="false" class="MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input" id="login-username" type="text" value="" /> instead
> ```

@aykutkantas hi,
afaik, all tests should be passed.

2023-12-09 21:25 UTC, aykutkantas commented
there is a fail at  app.test.js also. I think unit tests are working properly. For passing fail cases I needed to change something in login.js @ckertam. I will check for last fail case at login.test.js but we need to solve fail for app.test.js also.     

FAIL  src/App.test.js
  ● Console

    console.log
      Rendering Header

      at Header (src/components/header/header.js:33:11)

  ● renders learn react link

    TestingLibraryElementError: Unable to find an element with the text: /learn react/i. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

2023-12-09 21:27 UTC, aykutkantas commented
> @aykutkantas hi,
> 
> i ran
> 
> ```
> cd backend/frontend
> npm install
> npm run test
> ```
> 
> and i got this:
> 
> ![sistem-bulamiyor](https://private-user-images.githubusercontent.com/23168063/289312741-4c83b8bc-a4e0-46f4-8ebc-879cf90a6678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTc0ODIsIm5iZiI6MTcwMjE1NzE4MiwicGF0aCI6Ii8yMzE2ODA2My8yODkzMTI3NDEtNGM4M2I4YmMtYTRlMC00NmY0LThlYmMtODc5Y2Y5MGE2Njc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIxMjYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjk4NTY4ZmFlMDdhZDlkNzVhZGNjZGFkZjYwZjkyYmRkYzAxOGRiMjIxZDY0ZjA4OThlODRmYjEyZjUyMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nkxDzhR6LzgzDgm8RujS9rHswwHF2-rGEcooLwhukCk)
> 
> what should i do to overcome this warning?

if you want, we can look together on dc

2023-12-09 21:29 UTC, sadikkuzu commented
> @aykutkantas hi,
> 
> i ran
> 
> ```
> cd backend/frontend
> npm install
> npm run test
> ```
> 
> and i got this:
> 
> ![sistem-bulamiyor](https://private-user-images.githubusercontent.com/23168063/289312741-4c83b8bc-a4e0-46f4-8ebc-879cf90a6678.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTc0NTYsIm5iZiI6MTcwMjE1NzE1NiwicGF0aCI6Ii8yMzE2ODA2My8yODkzMTI3NDEtNGM4M2I4YmMtYTRlMC00NmY0LThlYmMtODc5Y2Y5MGE2Njc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIxMjU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNDZkM2Q4MGRkYzBkYzdmZDYzZGQ2MTkzNDNkNmJlNjNjYjZmNmZhNGNmMjMwODkxMzU4MzVlNDg2NDdmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k5pF-r9GcGq6WhSQR1Cz7h2EMmmnmMk6UUQXkrh21eo)
> 
> what should i do to overcome this warning?

Well, I could run within frontend container:

![frontend](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/fb5190d9-c809-438c-bb5a-c3ce481c6530)

Then now, we may focus on all passed tests.

2023-12-09 21:34 UTC, aykutkantas commented
Great! Is it about that we don't give a message "Login successful" when a user logged in? @sadikkuzu 

  ● Login component › handles successful login

    Unable to find an element with the text: /Login successful/. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

2023-12-09 21:54 UTC, sadikkuzu requested changes
Could you try those suggestions in `backend/frontend/src/pages/landing/Login.test.js`?

and also, in `backend/frontend/src/App.test.js`:

```javascript
import { render, screen } from '@testing-library/react';
import App from './App';

test('renders register link', () => {
  render(<App />);
  const linkElement = screen.getByText(/register/i);
  expect(linkElement).toBeInTheDocument();
});

```

2023-12-09 21:54 UTC, sadikkuzu commented on backend/frontend/src/pages/landing/Login.test.js
> +import { render, fireEvent, waitFor, screen } from '@testing-library/react';
```suggestion
import { render, fireEvent, waitFor, screen, act } from '@testing-library/react';
```

2023-12-09 21:54 UTC, sadikkuzu commented on backend/frontend/src/pages/landing/Login.test.js
> +      expect(screen.queryByLabelText('Username')).not.toBeInTheDocument();
```suggestion
      expect(screen.queryByLabelText('Username')).toBeInTheDocument();
```

2023-12-09 21:54 UTC, sadikkuzu commented on backend/frontend/src/pages/landing/Login.test.js
> +        expect(screen.queryByLabelText('Username')).not.toBeInTheDocument();
```suggestion
        expect(screen.queryByLabelText('Username')).toBeInTheDocument();
```

2023-12-09 22:02 UTC, aykutkantas commented
Login test is ok but app.test failed. 

<img width="1018" alt="Screenshot 2023-12-10 at 01 01 48" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/126410955/1c9e78db-4743-4bb9-a06e-131c6bd5e608">

 FAIL  src/App.test.js
  ● Console

    console.log
      Rendering Header

      at Header (src/components/header/header.js:33:11)

  ● renders learn react link

    TestingLibraryElementError: Unable to find an element with the text: /learn react/i. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

2023-12-09 22:05 UTC, sadikkuzu commented
@aykutkantas hi,
As I mentioned above in https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/254#pullrequestreview-1773861301
Could you please update `backend/frontend/src/App.test.js` file as below:

```javascript
import { render, screen } from '@testing-library/react';
import App from './App';

test('renders register link', () => {
  render(<App />);
  const linkElement = screen.getByText(/register/i);
  expect(linkElement).toBeInTheDocument();
});

```

2023-12-09 22:08 UTC, aykutkantas commented
Ok, all passed. :)

2023-12-10 16:56 UTC, ckertam approved these changes
Nice work! Also removing unneccesary things is perfect!

2023-12-10 16:57 UTC, ckertam commented
Also resolved the conflicts that is caused by #266 that is done by @oguzsenna

2023-12-10 18:53 UTC, sadikkuzu approved these changes
LGTM 🥂

2023-12-10 19:04 UTC, aykutkantas commented
@sadikkuzu @ckertam many thanks for your great support and guidance :)

2023-12-10 19:04 UTC, merged