Merge milestone 1 report
SWE574-Fall2023-Group1/SWE574-Fall2023-G1 pull request #94
Opened 2023-10-30 14:36 UTC by dbaslan

Can we merge to main to get the most up-to-date version of the milestone 1 report? (Report is almost finished, needs a few minor additions)

2023-10-30 14:38 UTC, sadikkuzu requested changes
This branch is out-of-date with the base branch
Merge the latest changes from main into this branch.

![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/385e306d-29cd-45c8-813e-4372ebc3f64f)

2023-10-30 14:41 UTC, sadikkuzu commented on reports/m1_group1.md
> +2. Communicated with the customer for feedback on requirements and workflow,
comma in the end

2023-10-30 14:42 UTC, sadikkuzu commented
Btw, my part hasn't finished yet. I'll add more items soon.

2023-10-30 14:53 UTC, ckertam requested changes
Let's wait until everyone has done with the report. I will make some changes too. Also, as I know @mert-aydin will make some changes too.

2023-11-01 21:37 UTC, sadikkuzu commented
pre-commit.ci autofix

2023-11-01 21:39 UTC, sadikkuzu commented
@dbaslan in hackmd, could you please pull from github after pre-commit.ci's auto-fixes?

2023-11-01 21:41 UTC, sadikkuzu commented
> This branch is out-of-date with the base branch Merge the latest changes from main into this branch.
> 
> ![image](https://user-images.githubusercontent.com/23168063/279093111-385e306d-29cd-45c8-813e-4372ebc3f64f.png)

@dbaslan if you are available now, we can look at it together in discord.

2023-11-01 21:55 UTC, dbaslan commented
Pulled pre-commit's autofixes, merged from main to reports, passed autocheck, awaiting review

2023-11-02 00:19 UTC, sadikkuzu reviewed
@dbaslan hi,
I've completed my individual-contributions part.
Could you please push the file from HackMD to GitHub?
Thanks in advance 🙏🏼

2023-11-02 09:06 UTC, dbaslan commented
Made final adjustments, awaiting review.

2023-11-02 09:10 UTC, sadikkuzu approved these changes
LGTM 👍🏼

2023-11-02 09:12 UTC, ckertam approved these changes
LGTM! 🥂

2023-11-02 09:13 UTC, oguzsenna approved these changes
Thanks for the effort

2023-11-02 09:13 UTC, merged

2023-11-02 09:14 UTC, sadikkuzu commented
Later on, let's add issue number at the end of commit messages.
(Here, for example, `Add final adjustments #64`)
![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/c1ef5b92-0129-4c4e-a842-1868055cae77)